data_source retail:
  type: bigquery
  connection:
    account_info_json_path: ${BIGQUERY_ACCOUNT_INFO_JSON_PATH}
    auth_scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
    project_id: '${BIGQUERY_PROJECT_ID}'
    dataset: ${BIGQUERY_DATASET}

soda_cloud:
  host: ${SODA_CLOUD_HOST}
  api_key_id: ${SODA_CLOUD_API_KEY_ID}
  api_key_secret: ${SODA_CLOUD_API_KEY_SECRET}
